# -*- coding: utf-8 -*-
{
    "name": "Environmental Certificates Management",
    "version": "18.0.0.0",
    "category": "Tools",
    "author": "Qulix",
    "company": "Qulix",
    "maintainer": "Qulix",
    "summary": "Environmental Certificates management",
    "depends": ["mail", "website", "contacts", "portal"],
    "data": [
        "security/environmental_certificates_groups.xml",
        "security/ir.model.access.csv",
        "data/certificate_types.xml",
        "data/ir_cron_data.xml",
        "data/mail_templates.xml",
        "data/certificate_categories.xml",
        "views/certificate_wizard_views.xml",
        "views/partner_views.xml",
        "views/certificate_type_views.xml",
        "views/certificate_categories_views.xml",
        "views/portal_views.xml",
        "views/portal_list_view.xml",
    ],
    "license": "AGPL-3",
    "installable": True,
    "auto_install": False,
    "application": True,
}
